apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  path: ./apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-lab
    namespace: default 
  targetNamespace: default
