apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/flux-cluster/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
